name: del

dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - tensorflow
    - tensorflow-datasets
    - jupyterlab
    - tqdm
    - pre-commit
